/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using Opennlp.Tools.Namefind;
using Opennlp.Tools.Util;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;

namespace Opennlp.Tools.Util.Featuregen
{
    /// <summary>
    /// Generates features if the tokens are recognized by the provided
    /// {@link TokenNameFinder}.
    /// </summary>
    internal class InSpanGenerator : AdaptiveFeatureGenerator
    {
        private readonly string prefix;
        private readonly TokenNameFinder finder;
        private string[] currentSentence;
        private Span[] currentNames;
        /// <summary>
        /// Initializes the current instance.
        /// </summary>
        /// <param name="prefix">the prefix is used to distinguish the generated features
        ///     from features generated by other instances of {@link InSpanGenerator}s.</param>
        /// <param name="finder">the {@link TokenNameFinder} used to detect the names.</param>
        public InSpanGenerator(string prefix, TokenNameFinder finder)
        {
            this.prefix = prefix;
            this.finder = finder;
        }

        public virtual void CreateFeatures(IList<string> features, string[] tokens, int index, string[] preds)
        {

            // cache results for sentence
            if (currentSentence != tokens)
            {
                currentSentence = tokens;
                currentNames = finder.Find(tokens);
            }


            // iterate over names and check if a span is contained
            foreach (Span currentName in currentNames)
            {
                if (currentName.Contains(index))
                {

                    // found a span for the current token
                    features.Add(prefix + ":w=dic");
                    features.Add(prefix + ":w=dic=" + tokens[index]);

                    // TODO: consider generation start and continuation features
                    break;
                }
            }
        }

        // LUCENENET: AdaptiveFeatureGenerator declares these as Java 8 default
        // methods; C# default interface implementations are unavailable on
        // netstandard2.0/net462, so the empty bodies are supplied here.
        public virtual void UpdateAdaptiveData(string[] tokens, string[] outcomes)
        {
        }

        public virtual void ClearAdaptiveData()
        {
        }
    }
}
